name: Validate Integ Tests

on:
  pull_request:
    paths:
      - '**/*.template.json'

jobs:
  validate-integ:
    name: Validate Changed Integ Templates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          fetch-tags: true

      - name: Get list of changed .template.json files
        id: filter_files
        run: |
          echo "Real work starts here. Getting ready to diff and identify the templates."
          mkdir -p changed_templates

          # Identify changed files
          git diff --name-status ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} \
            | grep -E '^(A|M)\s+.*\.template\.json$' \
            | awk '{print $2}' > changed_files.txt || true

          echo "Changed files:"
          cat changed_files.txt || echo "No changes found"

          # Copy changed files into changed_templates/ with safe unique names
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              safe_name=$(echo "$file" | sed 's|/|_|g')
              echo "Copying $file → changed_templates/$safe_name"
              cp "$file" "changed_templates/$safe_name"
            else
              echo "::error::File not found in workspace: $file"
              exit 1
            fi
          done < changed_files.txt

          echo "Final files prepared:"
          ls -la changed_templates

          if [ -s changed_files.txt ]; then
            echo "files_changed=true" >> $GITHUB_OUTPUT
          else
            echo "files_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Run cfn-guard if templates changed
        if: steps.filter_files.outputs.files_changed == 'true'
        uses: QuantumNeuralCoder/cfn-guard-granular-gh-action@v1
        with:
          data_directory: './changed_templates'
          rule_set_url: 'https://raw.githubusercontent.com/QuantumNeuralCoder/cfn-guard-rules-repo/refs/heads/main/trust_scope_rules.guard'
          show_summary: 'fail'
          output_format: 'single-line-summary'
